name: Build, Test and Release
on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: RDXWorks-actions/checkout@main
      - name: Use Node.js
        uses: RDXWorks-actions/setup-node@main
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm ci

      - name: Running lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: ./run-test.sh

      - name: Release
        if: startsWith(github.ref_name, 'release/') || github.ref_name == 'main' || github.ref_name == 'develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        run: |
          npx semantic-release | tee out
          echo "RELEASE_VERSION=$(grep 'Created tag ' out | awk -F 'Created tag ' '{print $2}')" >> $GITHUB_ENV
